local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
	s("cp", {
		t({
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"using vi = vector<int>;",
			"using vvi = vector<vector<int>>;",
			"using pi = pair<int, int>;",
			"using ll = long long;",
			"",
			"class Solution {",
			"public:",
			"    void solve() {",
			"        ",
		}),
		i(1, "code"),
		t({
			"",
			"    }",
			"};",
			"",
			"int main() {",
			"    ios::sync_with_stdio(false);",
			"    cin.tie(nullptr);",
			"    cout.tie(nullptr);",
			"    // freopen(\"name.in\", \"r\", stdin);",
			"    // freopen(\"name.out\", \"w\", stdout);",
			"    Solution s;",
			"    s.solve();",
			"    return 0;",
			"}",
		}),
	}),

	s("validNeighbors", {
		t({
			"vector<pair<int, int>> validNeighbors(int x, int y, vector<vector<int>> &graph) {",
			"    vector<pair<int, int>> neighbors;",
			"    vector<pair<int, int>> delta{{0, -1}, {-1, 0}, {0, 1}, {1, 0}};",
			"    int m = graph.size(), n = graph[0].size();",
			"    for (auto const &[dx, dy] : delta) {",
			"        int r = x + dx, c = y + dy;",
			"        if (r >= 0 && r < m && c >= 0 && c < n)",
			"            neighbors.push_back({r, c});",
			"    }",
			"    return neighbors;",
			"}",
		}),
	}),

	s("printAnything", {
		t({
			"template <typename T>",
			"struct is_vector : false_type {};",
			"",
			"template <typename U, typename Alloc>",
			"struct is_vector<vector<U, Alloc>> : true_type {};",
			"",
			"template <typename T>",
			"struct is_set : false_type {};",
			"",
			"template <typename U, typename Comp, typename Alloc>",
			"struct is_set<set<U, Comp, Alloc>> : true_type {};",
			"",
			"template <typename T>",
			"struct is_unordered_set : false_type {};",
			"",
			"template <typename U, typename Hash, typename KeyEq, typename Alloc>",
			"struct is_unordered_set<unordered_set<U, Hash, KeyEq, Alloc>> : true_type {};",
			"",
			"template <typename T>",
			"struct is_map : false_type {};",
			"",
			"template <typename K, typename V, typename Comp, typename Alloc>",
			"struct is_map<map<K, V, Comp, Alloc>> : true_type {};",
			"",
			"template <typename T>",
			"struct is_unordered_map : false_type {};",
			"",
			"template <typename K, typename V, typename Hash, typename KeyEq, typename Alloc>",
			"struct is_unordered_map<unordered_map<K, V, Hash, KeyEq, Alloc>> : true_type {};",
			"",
			"template <typename T>",
			"struct is_pair : false_type {};",
			"",
			"template <typename A, typename B>",
			"struct is_pair<pair<A, B>> : true_type {};",
			"",
			"template <typename T>",
			"void print(const T& data, const string& sep = \", \", const string& end = \"\\n\") {",
			"    if constexpr (",
			"        is_same_v<T, int> ||",
			"        is_same_v<T, long long> ||",
			"        is_same_v<T, char> ||",
			"        is_same_v<T, string> ||",
			"        is_same_v<T, double> ||",
			"        is_same_v<T, float> ||",
			"        is_same_v<T, bool>",
			"    ) {",
			"        cout << data << end;",
			"    } else if constexpr (is_pair<T>::value) {",
			"        cout << \"{\";",
			"        print(data.first, sep, \"\");",
			"        cout << sep;",
			"        print(data.second, sep, \"\");",
			"        cout << \"}\" << end;",
			"    } else if constexpr (",
			"        is_vector<T>::value ||",
			"        is_set<T>::value ||",
			"        is_unordered_set<T>::value",
			"    ) {",
			"        cout << \"{\";",
			"",
			"        bool first = true;",
			"        for (const auto& ele : data) {",
			"            if (!first) {",
			"                cout << sep;",
			"            }",
			"            first = false;",
			"            print(ele, sep, \"\");",
			"        }",
			"",
			"        cout << \"}\" << end;",
			"    } else if constexpr (",
			"        is_map<T>::value ||",
			"        is_unordered_map<T>::value",
			"    ) {",
			"        cout << \"{\";",
			"",
			"        bool first = true;",
			"        for (const auto& [key, value] : data) {",
			"            if (!first) {",
			"                cout << sep;",
			"            }",
			"            first = false;",
			"            cout << \"{\";",
			"            print(key, sep, \"\");",
			"            cout << \": \";",
			"            print(value, sep, \"\");",
			"            cout << \"}\";",
			"        }",
			"",
			"        cout << \"}\" << end;",
			"    }",
			"}",
		}),
	}),

	s("leettest", {
		t({
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"",
			"template <typename T> struct Deserialize;",
			"template <typename T> string serialize(const T &value);",
			"",
			"struct ListNode {",
			"    int val;",
			"    ListNode *next;",
			"    ListNode() : val(0), next(nullptr) {}",
			"    ListNode(int x) : val(x), next(nullptr) {}",
			"    ListNode(int x, ListNode *next) : val(x), next(next) {}",
			"};",
			"",
			"struct TreeNode {",
			"    int val;",
			"    TreeNode *left;",
			"    TreeNode *right;",
			"    TreeNode() : val(0), left(nullptr), right(nullptr) {}",
			"    TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}",
			"    TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}",
			"};",
			"",
			"string trim(const string &s) {",
			"    size_t l = 0, r = s.size();",
			"    while (l < r && isspace(static_cast<unsigned char>(s[l]))) ++l;",
			"    while (r > l && isspace(static_cast<unsigned char>(s[r - 1]))) --r;",
			"    return s.substr(l, r - l);",
			"}",
			"",
			"vector<string> split_lines(const string &block) {",
			"    vector<string> out;",
			"    istringstream in(block);",
			"    string line;",
			"    while (getline(in, line)) {",
			"        line = trim(line);",
			"        if (!line.empty()) out.push_back(line);",
			"    }",
			"    return out;",
			"}",
			"",
			"vector<string> split_top_level(const string &s) {",
			"    vector<string> out;",
			"    string cur;",
			"    int sq = 0;",
			"    bool in_str = false;",
			"    for (size_t i = 0; i < s.size(); ++i) {",
			"        char ch = s[i];",
			"        if (ch == '\"' && (i == 0 || s[i - 1] != '\\\\')) in_str = !in_str;",
			"        if (!in_str) {",
			"            if (ch == '[') ++sq;",
			"            else if (ch == ']') --sq;",
			"            else if (ch == ',' && sq == 0) {",
			"                out.push_back(trim(cur));",
			"                cur.clear();",
			"                continue;",
			"            }",
			"        }",
			"        cur.push_back(ch);",
			"    }",
			"    if (!cur.empty()) out.push_back(trim(cur));",
			"    if (out.size() == 1 && out[0].empty()) out.clear();",
			"    return out;",
			"}",
			"",
			"string strip_brackets(const string &s) {",
			"    string t = trim(s);",
			"    if (t.size() < 2 || t.front() != '[' || t.back() != ']') throw runtime_error(\"bad list: \" + t);",
			"    return trim(t.substr(1, t.size() - 2));",
			"}",
			"",
			"bool is_null_token(const string &s) {",
			"    string t = trim(s);",
			"    return t == \"null\" || t == \"nullptr\";",
			"}",
			"",
			"template <> struct Deserialize<int> { static int parse(const string &s) { return stoi(trim(s)); } };",
			"template <> struct Deserialize<long long> { static long long parse(const string &s) { return stoll(trim(s)); } };",
			"template <> struct Deserialize<string> {",
			"    static string parse(const string &s) {",
			"        string t = trim(s);",
			"        if (t.size() >= 2 && t.front() == '\"' && t.back() == '\"') return t.substr(1, t.size() - 2);",
			"        return t;",
			"    }",
			"};",
			"template <> struct Deserialize<bool> {",
			"    static bool parse(const string &s) {",
			"        string t = trim(s);",
			"        if (t == \"true\") return true;",
			"        if (t == \"false\") return false;",
			"        throw runtime_error(\"bad bool: \" + t);",
			"    }",
			"};",
			"",
			"template <typename T> struct Deserialize<vector<T>> {",
			"    static vector<T> parse(const string &s) {",
			"        vector<T> out;",
			"        for (const auto &x : split_top_level(strip_brackets(s))) out.push_back(Deserialize<T>::parse(x));",
			"        return out;",
			"    }",
			"};",
			"",
			"template <> struct Deserialize<ListNode *> {",
			"    static ListNode *parse(const string &s) {",
			"        vector<int> vals = Deserialize<vector<int>>::parse(s);",
			"        ListNode dummy;",
			"        ListNode *tail = &dummy;",
			"        for (int x : vals) {",
			"            tail->next = new ListNode(x);",
			"            tail = tail->next;",
			"        }",
			"        return dummy.next;",
			"    }",
			"};",
			"",
			"template <> struct Deserialize<TreeNode *> {",
			"    static TreeNode *parse(const string &s) {",
			"        string inner = strip_brackets(s);",
			"        vector<string> toks = split_top_level(inner);",
			"        if (toks.empty() || is_null_token(toks[0])) return nullptr;",
			"        TreeNode *root = new TreeNode(Deserialize<int>::parse(toks[0]));",
			"        queue<TreeNode *> q;",
			"        q.push(root);",
			"        size_t i = 1;",
			"        while (!q.empty() && i < toks.size()) {",
			"            TreeNode *cur = q.front();",
			"            q.pop();",
			"            if (i < toks.size() && !is_null_token(toks[i])) {",
			"                cur->left = new TreeNode(Deserialize<int>::parse(toks[i]));",
			"                q.push(cur->left);",
			"            }",
			"            ++i;",
			"            if (i < toks.size() && !is_null_token(toks[i])) {",
			"                cur->right = new TreeNode(Deserialize<int>::parse(toks[i]));",
			"                q.push(cur->right);",
			"            }",
			"            ++i;",
			"        }",
			"        return root;",
			"    }",
			"};",
			"",
			"template <typename T> T parse_value(const string &s) { return Deserialize<T>::parse(s); }",
			"",
			"template <> string serialize<int>(const int &v) { return to_string(v); }",
			"template <> string serialize<long long>(const long long &v) { return to_string(v); }",
			"template <> string serialize<bool>(const bool &v) { return v ? \"true\" : \"false\"; }",
			"template <> string serialize<string>(const string &v) { return \"\\\"\" + v + \"\\\"\"; }",
			"",
			"template <typename T> string serialize(const vector<T> &v) {",
			"    string out = \"[\";",
			"    for (size_t i = 0; i < v.size(); ++i) {",
			"        if (i) out += \",\";",
			"        out += serialize(v[i]);",
			"    }",
			"    out += \"]\";",
			"    return out;",
			"}",
			"",
			"template <> string serialize(ListNode *const &head) {",
			"    vector<int> vals;",
			"    for (ListNode *p = head; p != nullptr; p = p->next) vals.push_back(p->val);",
			"    return serialize(vals);",
			"}",
			"",
			"template <> string serialize(TreeNode *const &root) {",
			"    if (root == nullptr) return \"[]\";",
			"    vector<string> vals;",
			"    queue<TreeNode *> q;",
			"    q.push(root);",
			"    while (!q.empty()) {",
			"        TreeNode *cur = q.front();",
			"        q.pop();",
			"        if (cur == nullptr) {",
			"            vals.push_back(\"null\");",
			"            continue;",
			"        }",
			"        vals.push_back(to_string(cur->val));",
			"        q.push(cur->left);",
			"        q.push(cur->right);",
			"    }",
			"    while (!vals.empty() && vals.back() == \"null\") vals.pop_back();",
			"    string out = \"[\";",
			"    for (size_t i = 0; i < vals.size(); ++i) {",
			"        if (i) out += \",\";",
			"        out += vals[i];",
			"    }",
			"    out += \"]\";",
			"    return out;",
			"}",
			"",
			"template <typename... Ts> string serialize(const tuple<Ts...> &tp) {",
			"    string out = \"[\";",
			"    bool first = true;",
			"    apply([&](const auto &...vals) {",
			"        ((out += (first ? \"\" : \",\") + serialize(vals), first = false), ...);",
			"    }, tp);",
			"    out += \"]\";",
			"    return out;",
			"}",
			"",
			"template <typename Tuple, size_t... I>",
			"Tuple parse_input_case_impl(const vector<string> &lines, size_t off, index_sequence<I...>) {",
			"    return Tuple{parse_value<tuple_element_t<I, Tuple>>(lines[off + I])...};",
			"}",
			"",
			"template <typename Tuple> vector<Tuple> parse_input_cases(const string &block) {",
			"    vector<string> lines = split_lines(block);",
			"    constexpr size_t arity = tuple_size_v<Tuple>;",
			"    static_assert(arity > 0, \"InputTuple cannot be empty\");",
			"    if (lines.size() % arity != 0) throw runtime_error(\"input lines not divisible by InputTuple arity\");",
			"    vector<Tuple> out;",
			"    for (size_t i = 0; i < lines.size(); i += arity) {",
			"        out.push_back(parse_input_case_impl<Tuple>(lines, i, make_index_sequence<arity>{}));",
			"    }",
			"    return out;",
			"}",
			"",
			"template <typename Tuple, size_t... I>",
			"Tuple parse_output_line_impl(const string &line, index_sequence<I...>) {",
			"    constexpr size_t arity = sizeof...(I);",
			"    static_assert(arity > 0, \"OutputTuple cannot be empty\");",
			"    if constexpr (arity == 1) {",
			"        using Only = tuple_element_t<0, Tuple>;",
			"        string t = trim(line);",
			"        try {",
			"            return Tuple{parse_value<Only>(t)};",
			"        } catch (const exception &) {",
			"            if (!(t.size() >= 2 && t.front() == '[' && t.back() == ']')) throw;",
			"            auto toks = split_top_level(strip_brackets(t));",
			"            if (toks.size() != 1) throw;",
			"            return Tuple{parse_value<Only>(toks[0])};",
			"        }",
			"    }",
			"    auto toks = split_top_level(strip_brackets(line));",
			"    if (toks.size() != arity) throw runtime_error(\"output arity mismatch in line: \" + line);",
			"    return Tuple{parse_value<tuple_element_t<I, Tuple>>(toks[I])...};",
			"}",
			"",
			"template <typename Tuple> vector<Tuple> parse_output_cases(const string &block) {",
			"    vector<Tuple> out;",
			"    for (const auto &line : split_lines(block)) {",
			"        out.push_back(parse_output_line_impl<Tuple>(line, make_index_sequence<tuple_size_v<Tuple>>{}));",
			"    }",
			"    return out;",
			"}",
			"",
			"class Solution {",
			"public:",
			"    // paste lc method(s) here",
			"};",
			"",
			"int main() {",
			"    using InputTuple = tuple<",
		}),
		i(1, "vector<int>, int"),
		t({
			">;",
			"    using OutputTuple = tuple<",
		}),
		i(2, "int"),
		t({
			">;",
			"",
			"    const string raw_inputs = R\"(",
			"// LC style input: one arg per line, grouped by InputTuple arity",
			"// case1-arg1",
			"// case1-arg2",
			"// case2-arg1",
			"// case2-arg2",
			")\";",
			"",
			"    const string raw_outputs = R\"(",
			"// one output line per case",
			"// for tuple<single>, plain line is enough: 4",
			"// for tuple<multi>, use brackets: [4,\"ok\"]",
			")\";",
			"",
			"    auto inputs = parse_input_cases<InputTuple>(raw_inputs);",
			"    auto outputs = parse_output_cases<OutputTuple>(raw_outputs);",
			"    if (inputs.size() != outputs.size()) throw runtime_error(\"input/output count mismatch\");",
			"",
			"    const string C_RESET  = \"\\033[0m\";",
			"    const string C_RED    = \"\\033[31m\";",
			"    const string C_GREEN  = \"\\033[32m\";",
			"    const string C_YELLOW = \"\\033[33m\";",
			"",
			"    Solution sol;",
			"    bool ok = true;",
			"    for (size_t i = 0; i < inputs.size(); ++i) {",
			"        // replace METHOD_NAME with your first public Solution method",
			"        auto actual = apply([&](auto&&... args) { return OutputTuple{sol.METHOD_NAME(args...)}; }, inputs[i]);",
			"        if (serialize(actual) != serialize(outputs[i])) {",
			"            ok = false;",
			"            cerr << C_RED << \"Case \" << (i + 1) << C_RESET << \" FAIL\\n\";",
			"            cerr << C_YELLOW << \"expected: \" << C_RESET << serialize(outputs[i]) << \"\\n\";",
			"            cerr << C_YELLOW << \"actual:   \" << C_RESET << serialize(actual) << \"\\n\";",
			"        } else {",
			"            cout << C_GREEN << \"Case \" << (i + 1) << C_RESET << \" PASS\\n\";",
			"        }",
			"    }",
			"",
			"    if (ok) cout << \"PASS\\n\";",
			"    else cout << \"FAIL\\n\";",
			"    return ok ? 0 : 1;",
			"}",
		}),
	}),
}
